embedding_size: 64
feat_embed_dim: 64

# n_layers: [1, 2]
n_layers: [2]
# dropout: [0.3, 0.5]
dropout: [0.3]
# reg_weight: [0.1, 0.01]
reg_weight: [0.01]
cl_weight: 2.0
epochs: 1
use_neg_sampling: True

hyper_parameters: ["n_layers", "reg_weight", "dropout"]

