embedding_size: 64
latent_embedding: 64

n_layers: 3
# reg_weight: [0.1, 0.01, 0.001, 0.0001, 0.00001]
reg_weight: [0.00001]

# learning_rate: [1, 0.1, 0.01, 0.001, 0.0001]
learning_rate: [0.001]

hyper_parameters: ["reg_weight", "learning_rate"]
epochs: 80
train_batch_size: 1024